= A Deep Dive into Spring Application Events

This repository contains the sample code for my talk "A Deep Dive into Spring Application Events".

image::https://github.com/odrotbohm/spring-events-deep-dive/workflows/Java%20CI%20with%20Maven/badge.svg[Build status]

The code base is organized following the three major parts of the talk

. **Fundamentals** (`….fundamentals`) -- contains samples of the fundamental API building blocks like `ApplicationEventPublisher`, `ApplicationListener`, `@EventListener`.
It also shows the usage of the Spring Data aggregate event publication support.
. **Transactions** (`….transactions`) -- contains samples for using `@TransactionalEventListener`.
The tests contain cases for successful execution and error scenarios (see <<demo.adoc, the demo rundown>> for details).
. **Architecture** (`….architecture`) -- contains a comparing sample for how to replace direct component interaction with event publication.

WARNING: Parts of this code are currently based on prototypical implementations that rely on snapshots, i.e. it might temporarily not build due to some code rearrangements.

== Resources

* Slide deck -- https://speakerdeck.com/olivergierke/a-deep-dive-into-spring-application-events
* Moduliths -- https://github.com/odrotbohm/moduliths
* Spring Domain Events -- https://github.com/odrotbohm/spring-domain-events
